class Constants:
    WELCOME = "Варяг. Текстовая RPG.\n\n"
    COMMAND_TEMPLATE = "[{0}] {1}"
    CREATE_NEW_OR_LOAD_HERO = "Выберите героя для загрузки или создайте нового"
    CREATE_NEW_PLAYER = "Создать нового героя"
    HERO_IS_LOADED = "Загружен герой {0}"
    ENTER_HERO_NAME = "Введите имя героя: "
    HERO_CREATED = "Герой {0} создан"
    ENTER_COMMAND_NUMBER = "Введите номер команды"
    YOUR_ANSWER = "Выберите ответ:"
    NEW_STUFF_GAINED = "Вы получили {0}"
    CHARACTER_HIT = "{0} атакует {1} на {2} ОЖ (Осталось {3} ОЖ)"
    CHARACTER_MISS = "{0} промахнулся"
    CHARACTER_CRITICAL_FAIL = "{0} критический промах"
    CHARACTER_IS_DEAD = "{0} мертв"
    CHARACTER_ATTACK = "{0} атакует {1}"
    CHOOSE_BATTLE_ACTION = "Твои действия?"

    PROMPT = ">"
    SAVE_DIRECTORY = "players"
